-- 1: successful from 5H4MvAsobfZ6bBCDyj5dsrWYLrA8HrRzaqa9p61UXtxMhSCY to 5CSbpCKSTvZefZYddesUQ9w6NDye2PHbf12MwBZGBgzGeGoo
INSERT INTO transaction (block_number,
                         chain_type,
                         extrinsic_index,
                         created_on,
                         from_address,
                         to_address,
                         transfer_value,
                         tip,
                         inclusion_fee,
                         reserved,
                         pallet,
                         method,
                         successful,
                         type)
VALUES (1,
        'Solo',
        1,
        '2021-07-19 15:17:11.000000',
        '5H4MvAsobfZ6bBCDyj5dsrWYLrA8HrRzaqa9p61UXtxMhSCY',
        '5CSbpCKSTvZefZYddesUQ9w6NDye2PHbf12MwBZGBgzGeGoo',
        13245000000,
        0,
        125000149,
        0,
        'balances',
        'transfer',
        true,
        'EXTRINSIC');

-- 2: failed from 5DPPdRwkgigKt2L7jxRfAoV4tfS89KgXsx47Wk3Kat5K6xPg to 5H4MvAsobfZ6bBCDyj5dsrWYLrA8HrRzaqa9p61UXtxMhSCY
INSERT INTO transaction (block_number,
                         chain_type,
                         extrinsic_index,
                         created_on,
                         from_address,
                         to_address,
                         transfer_value,
                         tip,
                         inclusion_fee,
                         reserved,
                         pallet,
                         method,
                         successful,
                         error_section,
                         error_name,
                         error_details,
                         type)
VALUES (2,
        'Solo',
        1,
        '2021-07-20 15:17:11.000000',
        '5DPPdRwkgigKt2L7jxRfAoV4tfS89KgXsx47Wk3Kat5K6xPg',
        '5H4MvAsobfZ6bBCDyj5dsrWYLrA8HrRzaqa9p61UXtxMhSCY',
        0,
        0,
        125000141,
        23,
        'assets',
        'setMetadata',
        false,
        'balances',
        'SomeError',
        'with many details',
        'EXTRINSIC');

--- 3: Tokens record fees (requester side)
INSERT INTO transaction (block_number,
                         chain_type,
                         extrinsic_index,
                         created_on,
                         from_address,
                         to_address,
                         transfer_value,
                         tip,
                         inclusion_fee,
                         tokens_record_fee,
                         reserved,
                         pallet,
                         method,
                         successful,
                         type,
                         hidden_from)
VALUES (3,
        'Solo',
        1,
        '2021-07-21 15:17:11.000000',
        '5DPPdRwkgigKt2L7jxRfAoV4tfS89KgXsx47Wk3Kat5K6xPg',
        '5H4MvAsobfZ6bBCDyj5dsrWYLrA8HrRzaqa9p61UXtxMhSCY',
        0,
        0,
        0,
        100,
        0,
        'logionLoc',
        'addTokensRecord',
        true,
        'TOKENS_RECORD_FEE',
        'TO');

--- 4: Tokens record fees (beneficiary side)
INSERT INTO transaction (block_number,
                         chain_type,
                         extrinsic_index,
                         created_on,
                         from_address,
                         to_address,
                         transfer_value,
                         tip,
                         inclusion_fee,
                         reserved,
                         pallet,
                         method,
                         successful,
                         type,
                         hidden_from)
VALUES (3,
        'Solo',
        1,
        '2021-07-21 15:17:11.000000',
        '5DPPdRwkgigKt2L7jxRfAoV4tfS89KgXsx47Wk3Kat5K6xPg',
        '5H4MvAsobfZ6bBCDyj5dsrWYLrA8HrRzaqa9p61UXtxMhSCY',
        50,
        0,
        0,
        0,
        'logionLoc',
        'addTokensRecord',
        true,
        'TOKENS_RECORD_FEE',
        'FROM');
