name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install exiftool
          uses: ConorMacBride/install-package@v1.1.0
          with:
            apt: libimage-exiftool-perl
        - name: Build and test
          run: |
            yarn install --immutable
            yarn test
            yarn build
